### ISSUE TITLE
关于TSM的尺寸问题

### ISSUE THREAD

**Issue by zzwei1** [ZJCV/TSM#1]
您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？

**Comment by zjykzj** [comment]
> 您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？

首先对于2D卷积，它的输入就是(N, C, H, W)，所以对于数据片段（B, C, T, H, W），需要转换成（BT, C, H, W）输入

其次TSM的关键在于时序移位模块，该模块应用于Backbone，是可插拔设计，在计算过程中会将（BT, C, H, W）再切分为（B, T, C, H, W）进行时序移位操作

**Comment by zzwei1** [comment]
> > 您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？
> 
> 首先对于2D卷积，它的输入就是(N, C, H, W)，所以对于数据片段（B, C, T, H, W），需要转换成（BT, C, H, W）输入
> 
> 其次TSM的关键在于时序移位模块，该模块应用于Backbone，是可插拔设计，在计算过程中会将（BT, C, H, W）再切分为（B, T, C, H, W）进行时序移位操作

感谢您回复！
这两天我又看了一下代码，确实如您所说，在计算过程中会将数据再切分为（B, T, C, H, W）进行时序移位操作。我又找了一些其他人的实现方法，看有的是将(B,T,C,H,W)view成(B,TC,H,W)这种形式，但是他temporal_shift部分代码与原作者完全没变化，还是按照（BT, C, H, W）切分为（B, T, C, H, W）的方法去实现的，就很奇怪。
如果将数据转换成(BT, C, H, W)输入,那相应的标签维度是不是也得扩展成（BT,1）这种形式，因为之前标签维度是B。

**Comment by zjykzj** [comment]
> > > 您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？
> > 
> > 
> > 首先对于2D卷积，它的输入就是(N, C, H, W)，所以对于数据片段（B, C, T, H, W），需要转换成（BT, C, H, W）输入
> > 其次TSM的关键在于时序移位模块，该模块应用于Backbone，是可插拔设计，在计算过程中会将（BT, C, H, W）再切分为（B, T, C, H, W）进行时序移位操作
> 
> 感谢您回复！
> 这两天我又看了一下代码，确实如您所说，在计算过程中会将数据再切分为（B, T, C, H, W）进行时序移位操作。我又找了一些其他人的实现方法，看有的是将(B,T,C,H,W)view成(B,TC,H,W)这种形式，但是他temporal_shift部分代码与原作者完全没变化，还是按照（BT, C, H, W）切分为（B, T, C, H, W）的方法去实现的，就很奇怪。
> 如果将数据转换成(BT, C, H, W)输入,那相应的标签维度是不是也得扩展成（BT,1）这种形式，因为之前标签维度是B。

在网络最后还是会转换成(BT, C, H, W) -> (B, T, C, H, W)，然后对T维度进行融合得到(B, C, H, W)

**Comment by zzwei1** [comment]
> > > > 您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？
> > > 
> > > 
> > > 首先对于2D卷积，它的输入就是(N, C, H, W)，所以对于数据片段（B, C, T, H, W），需要转换成（BT, C, H, W）输入
> > > 其次TSM的关键在于时序移位模块，该模块应用于Backbone，是可插拔设计，在计算过程中会将（BT, C, H, W）再切分为（B, T, C, H, W）进行时序移位操作
> > 
> > 
> > 感谢您回复！
> > 这两天我又看了一下代码，确实如您所说，在计算过程中会将数据再切分为（B, T, C, H, W）进行时序移位操作。我又找了一些其他人的实现方法，看有的是将(B,T,C,H,W)view成(B,TC,H,W)这种形式，但是他temporal_shift部分代码与原作者完全没变化，还是按照（BT, C, H, W）切分为（B, T, C, H, W）的方法去实现的，就很奇怪。
> > 如果将数据转换成(BT, C, H, W)输入,那相应的标签维度是不是也得扩展成（BT,1）这种形式，因为之前标签维度是B。
> 
> 在网络最后还是会转换成(BT, C, H, W) -> (B, T, C, H, W)，然后对T维度进行融合得到(B, C, H, W)

也就是说，假设我一开始数据维度是(B,T,C,H,W),需要view成(BT,C,H,W)输入2D网络，标签不用变。是这样不？

**Comment by zjykzj** [comment]
> > > > > 您好，关于使用TSM的一个输入尺寸问题想请教一下您。我看TSM源码里，他的输入尺寸是（BT,C,H,W）的形状，那么对于一个视频形式的数据X（由多帧连续图片构成），其shape为（B,T,C,H,W），怎样操作才能将他输入进2D网络呢？直接用X.view(BT,C,H,W)吗？还是X.view(B,TC,H,W)呢？
> > > > 
> > > > 
> > > > 首先对于2D卷积，它的输入就是(N, C, H, W)，所以对于数据片段（B, C, T, H, W），需要转换成（BT, C, H, W）输入
> > > > 其次TSM的关键在于时序移位模块，该模块应用于Backbone，是可插拔设计，在计算过程中会将（BT, C, H, W）再切分为（B, T, C, H, W）进行时序移位操作
> > > 
> > > 
> > > 感谢您回复！
> > > 这两天我又看了一下代码，确实如您所说，在计算过程中会将数据再切分为（B, T, C, H, W）进行时序移位操作。我又找了一些其他人的实现方法，看有的是将(B,T,C,H,W)view成(B,TC,H,W)这种形式，但是他temporal_shift部分代码与原作者完全没变化，还是按照（BT, C, H, W）切分为（B, T, C, H, W）的方法去实现的，就很奇怪。
> > > 如果将数据转换成(BT, C, H, W)输入,那相应的标签维度是不是也得扩展成（BT,1）这种形式，因为之前标签维度是B。
> > 
> > 
> > 在网络最后还是会转换成(BT, C, H, W) -> (B, T, C, H, W)，然后对T维度进行融合得到(B, C, H, W)
> 
> 也就是说，假设我一开始数据维度是(B,T,C,H,W),需要view成(BT,C,H,W)输入2D网络，标签不用变。是这样不？

在我的实现里面，输入数据的格式是(B, C, T, H, W)，标签格式为（B）

**Comment by zzwei1** [comment]
> 在我的实现里面，输入数据的格式是(B, C, T, H, W)，标签格式为（B）

这个我理解了。现在我没搞懂的是，对格式为(B, C, T, H, W)的输入和格式为(B)的标签分别做了什么样的操作，使得(B, C, T, H, W)能输入到2D网络？

**Comment by zjykzj** [comment]
> > 在我的实现里面，输入数据的格式是(B, C, T, H, W)，标签格式为（B）
> 
> 这个我理解了。现在我没搞懂的是，对格式为(B, C, T, H, W)的输入和格式为(B)的标签分别做了什么样的操作，使得(B, C, T, H, W)能输入到2D网络？

需要进行维度转换
(B, C, T,  H, W) -> (B, T, C, H, W) -> (BT, C, H, W)

**Comment by zzwei1** [comment]
> > > 在我的实现里面，输入数据的格式是(B, C, T, H, W)，标签格式为（B）
> > 
> > 
> > 这个我理解了。现在我没搞懂的是，对格式为(B, C, T, H, W)的输入和格式为(B)的标签分别做了什么样的操作，使得(B, C, T, H, W)能输入到2D网络？
> 
> 需要进行维度转换
> (B, C, T, H, W) -> (B, T, C, H, W) -> (BT, C, H, W)

了解了，十分感谢！我再去尝试一下！
